name: Actividad Enriquecimiento de Datos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: paso3 - actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .
      - name: paso5 - Ejecutar script act1
        run: python src\ingestion.py
      - name: paso6 - Ejecutar script act2
        run: python src\cleaning.py 
      - name: paso7 - Ejecutar script act3
        run: python src\enrichement.py 

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Entrega act1, act2 y act3
          commit_user_name: Julio Muñoz [GitHub Actions]
          commit_user_email: julio.munozr@est.iudigital.edu.co
          commit_author: Julio Muñoz <julio.munozr@est.iudigital.edu.co>
